site_name: IPTV Gateway
site_url: https://mazzz1y.github.io/iptv-gateway
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  custom_dir: docs/overrides
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.instant
    - toc.follow

markdown_extensions:
  - toc:
      anchorlink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Configuration:
      - Overview: config.md
      - Logs: config/logs.md
      - Cache: config/cache.md
      - Server: config/server.md
      - URL Generator: config/url_generator.md
      - Proxy: config/proxy.md
      - Playlists: config/playlists.md
      - EPGs: config/epgs.md
      - Rules:
          - Overview: config/rules/index.md
          - Set Field: config/rules/set_field.md
          - Remove Field: config/rules/remove_field.md
          - Remove Channel: config/rules/remove_channel.md
          - Mark Hidden: config/rules/mark_hidden.md
          - Remove Duplicates: config/rules/remove_duplicates.md
          - Sort: config/rules/sort.md
          - When: config/rules/when.md
      - Presets: config/presets.md
      - Clients: config/clients.md
      - Common Fields: config/common.md
  - Examples: config/examples.md
  - Metrics: metrics.md
